/* tslint:disable */
/* eslint-disable */
/**
 * Pickup API
 * # Authorization   Pickup API accepts one type of authentication   <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtraGroupClass } from './ExtraGroupClass';
import {
    ExtraGroupClassFromJSON,
    ExtraGroupClassFromJSONTyped,
    ExtraGroupClassToJSON,
} from './ExtraGroupClass';
import type { ItemTimeSlotClass } from './ItemTimeSlotClass';
import {
    ItemTimeSlotClassFromJSON,
    ItemTimeSlotClassFromJSONTyped,
    ItemTimeSlotClassToJSON,
} from './ItemTimeSlotClass';

/**
 * 
 * @export
 * @interface ItemClass
 */
export interface ItemClass {
    /**
     * Item id that will be used for cart building on /cart route
     * @type {string}
     * @memberof ItemClass
     */
    id: string;
    /**
     * List of grouped extras of an item
     * @type {Array<ExtraGroupClass>}
     * @memberof ItemClass
     */
    extraGroup?: Array<ExtraGroupClass>;
    /**
     * Random unique item code
     * @type {string}
     * @memberof ItemClass
     */
    itemCode: string;
    /**
     * Indicates the item is bulky and will automatically select car on checkout if order type is delivery
     * @type {boolean}
     * @memberof ItemClass
     */
    isBulk?: boolean;
    /**
     * Indicates if item is part of meal plan order type
     * @type {boolean}
     * @memberof ItemClass
     */
    isMealPlan?: boolean;
    /**
     * Store off dates helper
     * @type {Array<string>}
     * @memberof ItemClass
     */
    offDates?: Array<string>;
    /**
     * Maximum number of allowed purchase of the item across all platform per day
     * @type {number}
     * @memberof ItemClass
     */
    itemLimitPerDay?: number;
    /**
     * Maximum number of allowed purchase of the item across all platform per time slot
     * @type {Array<ItemTimeSlotClass>}
     * @memberof ItemClass
     */
    itemLimitPerTimeSlot?: Array<ItemTimeSlotClass>;
    /**
     * Store which this item belongs to, can be used for filtering
     * @type {string}
     * @memberof ItemClass
     */
    storeId?: string;
    /**
     * The name of the item
     * @type {string}
     * @memberof ItemClass
     */
    name: string;
    /**
     * The description of the item
     * @type {string}
     * @memberof ItemClass
     */
    description: string;
    /**
     * The nominated item display image in url form
     * @type {string}
     * @memberof ItemClass
     */
    imageUrl: string;
    /**
     * The item discount description
     * @type {string}
     * @memberof ItemClass
     */
    discountDescription?: string;
    /**
     * The peso value of the current active item discount. If discount_type is rawDiscount, this is equal to the discount_value. If percentDiscount, this is equal to the regular_price multiplied to the discount_value/100.
     * @type {string}
     * @memberof ItemClass
     */
    activeDiscount?: string;
    /**
     * The active price of the item, if there is an active discount, this should be equal to the discounted_price, if there is no active discount, this should be equal to the regular price
     * @type {string}
     * @memberof ItemClass
     */
    price: string;
    /**
     * The type of discount applied ("noDiscount", "rawDiscount", "percentDiscount")
     * @type {string}
     * @memberof ItemClass
     */
    discountType?: string;
    /**
     * The value of the discount applied. For example if discount_value is "20", if discount_type is percentDiscount, this means 20% off. If discount_type is rawDiscount, this means P20.00 off.
     * @type {string}
     * @memberof ItemClass
     */
    discountValue?: string;
    /**
     * The peso value of the item, applying the active_discount to the regular_price.
     * @type {string}
     * @memberof ItemClass
     */
    discountedPrice: string;
    /**
     * The peso value of the item without any discounts.
     * @type {string}
     * @memberof ItemClass
     */
    regularPrice?: string;
    /**
     * Item tags
     * @type {Array<string>}
     * @memberof ItemClass
     */
    tags: Array<string>;
    /**
     * Indicates item to not be shown to customers on an off-date
     * @type {boolean}
     * @memberof ItemClass
     */
    isVisibleOnOffDate?: boolean;
    /**
     * Item is available for order
     * @type {boolean}
     * @memberof ItemClass
     */
    available?: boolean;
    /**
     * Item category, should be in store category list
     * @type {string}
     * @memberof ItemClass
     */
    category?: string;
    /**
     * Indicates if item has an extra group to be shown as part of the order
     * @type {boolean}
     * @memberof ItemClass
     */
    extras?: boolean;
    /**
     * Indicates if item should be visible to the customer
     * @type {boolean}
     * @memberof ItemClass
     */
    visible?: boolean;
}

/**
 * Check if a given object implements the ItemClass interface.
 */
export function instanceOfItemClass(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "itemCode" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "imageUrl" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "discountedPrice" in value;
    isInstance = isInstance && "tags" in value;

    return isInstance;
}

export function ItemClassFromJSON(json: any): ItemClass {
    return ItemClassFromJSONTyped(json, false);
}

export function ItemClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemClass {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'extraGroup': !exists(json, 'extra_group') ? undefined : ((json['extra_group'] as Array<any>).map(ExtraGroupClassFromJSON)),
        'itemCode': json['item_code'],
        'isBulk': !exists(json, 'is_bulk') ? undefined : json['is_bulk'],
        'isMealPlan': !exists(json, 'is_meal_plan') ? undefined : json['is_meal_plan'],
        'offDates': !exists(json, 'off_dates') ? undefined : json['off_dates'],
        'itemLimitPerDay': !exists(json, 'item_limit_per_day') ? undefined : json['item_limit_per_day'],
        'itemLimitPerTimeSlot': !exists(json, 'item_limit_per_time_slot') ? undefined : ((json['item_limit_per_time_slot'] as Array<any>).map(ItemTimeSlotClassFromJSON)),
        'storeId': !exists(json, 'store_id') ? undefined : json['store_id'],
        'name': json['name'],
        'description': json['description'],
        'imageUrl': json['image_url'],
        'discountDescription': !exists(json, 'discount_description') ? undefined : json['discount_description'],
        'activeDiscount': !exists(json, 'active_discount') ? undefined : json['active_discount'],
        'price': json['price'],
        'discountType': !exists(json, 'discount_type') ? undefined : json['discount_type'],
        'discountValue': !exists(json, 'discount_value') ? undefined : json['discount_value'],
        'discountedPrice': json['discounted_price'],
        'regularPrice': !exists(json, 'regular_price') ? undefined : json['regular_price'],
        'tags': json['tags'],
        'isVisibleOnOffDate': !exists(json, 'is_visible_on_off_date') ? undefined : json['is_visible_on_off_date'],
        'available': !exists(json, 'available') ? undefined : json['available'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'extras': !exists(json, 'extras') ? undefined : json['extras'],
        'visible': !exists(json, 'visible') ? undefined : json['visible'],
    };
}

export function ItemClassToJSON(value?: ItemClass | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'extra_group': value.extraGroup === undefined ? undefined : ((value.extraGroup as Array<any>).map(ExtraGroupClassToJSON)),
        'item_code': value.itemCode,
        'is_bulk': value.isBulk,
        'is_meal_plan': value.isMealPlan,
        'off_dates': value.offDates,
        'item_limit_per_day': value.itemLimitPerDay,
        'item_limit_per_time_slot': value.itemLimitPerTimeSlot === undefined ? undefined : ((value.itemLimitPerTimeSlot as Array<any>).map(ItemTimeSlotClassToJSON)),
        'store_id': value.storeId,
        'name': value.name,
        'description': value.description,
        'image_url': value.imageUrl,
        'discount_description': value.discountDescription,
        'active_discount': value.activeDiscount,
        'price': value.price,
        'discount_type': value.discountType,
        'discount_value': value.discountValue,
        'discounted_price': value.discountedPrice,
        'regular_price': value.regularPrice,
        'tags': value.tags,
        'is_visible_on_off_date': value.isVisibleOnOffDate,
        'available': value.available,
        'category': value.category,
        'extras': value.extras,
        'visible': value.visible,
    };
}

