/* tslint:disable */
/* eslint-disable */
/**
 * Pickup API
 * # Authorization   Pickup API accepts one type of authentication   <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemInventoryEntity
 */
export interface ItemInventoryEntity {
    /**
     * Number of available item quantity
     * @type {number}
     * @memberof ItemInventoryEntity
     */
    available: number;
}

/**
 * Check if a given object implements the ItemInventoryEntity interface.
 */
export function instanceOfItemInventoryEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "available" in value;

    return isInstance;
}

export function ItemInventoryEntityFromJSON(json: any): ItemInventoryEntity {
    return ItemInventoryEntityFromJSONTyped(json, false);
}

export function ItemInventoryEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemInventoryEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'available': json['available'],
    };
}

export function ItemInventoryEntityToJSON(value?: ItemInventoryEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'available': value.available,
    };
}

