/* tslint:disable */
/* eslint-disable */
/**
 * Pickup API
 * # Authorization   Pickup API accepts one type of authentication   <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorePartialClass } from './StorePartialClass';
import {
    StorePartialClassFromJSON,
    StorePartialClassFromJSONTyped,
    StorePartialClassToJSON,
} from './StorePartialClass';

/**
 * 
 * @export
 * @interface StoresEntity
 */
export interface StoresEntity {
    /**
     * 
     * @type {boolean}
     * @memberof StoresEntity
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoresEntity
     */
    hasPrevPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof StoresEntity
     */
    totalPages: number;
    /**
     * 
     * @type {Array<StorePartialClass>}
     * @memberof StoresEntity
     */
    result: Array<StorePartialClass>;
    /**
     * 
     * @type {number}
     * @memberof StoresEntity
     */
    page: number;
}

/**
 * Check if a given object implements the StoresEntity interface.
 */
export function instanceOfStoresEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasNextPage" in value;
    isInstance = isInstance && "hasPrevPage" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "page" in value;

    return isInstance;
}

export function StoresEntityFromJSON(json: any): StoresEntity {
    return StoresEntityFromJSONTyped(json, false);
}

export function StoresEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoresEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasNextPage': json['has_next_page'],
        'hasPrevPage': json['has_prev_page'],
        'totalPages': json['total_pages'],
        'result': ((json['result'] as Array<any>).map(StorePartialClassFromJSON)),
        'page': json['page'],
    };
}

export function StoresEntityToJSON(value?: StoresEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'has_next_page': value.hasNextPage,
        'has_prev_page': value.hasPrevPage,
        'total_pages': value.totalPages,
        'result': ((value.result as Array<any>).map(StorePartialClassToJSON)),
        'page': value.page,
    };
}

